import Head from "next/head";
import Link from "next/link";
import Nav from "../components/Nav";
import HeroSection from "../components/HeroSection";
import About from "../components/About";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio DS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <HeroSection />

      <main>
        <About />
        <Projects />
        <Skills />
      </main>

      <Footer />
    </div>
  );
}
